package com.example.codeclan.next_best_friend.components;

import com.example.codeclan.next_best_friend.models.Breeder;
import com.example.codeclan.next_best_friend.models.Dog;
import com.example.codeclan.next_best_friend.models.Listing;
import com.example.codeclan.next_best_friend.models.User;
import com.example.codeclan.next_best_friend.repositories.BreederRepository;
import com.example.codeclan.next_best_friend.repositories.DogRepository;
import com.example.codeclan.next_best_friend.repositories.ListingRepository;
import com.example.codeclan.next_best_friend.repositories.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.ApplicationArguments;
import org.springframework.boot.ApplicationRunner;
import org.springframework.security.crypto.bcrypt.BCrypt;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;

import java.util.ArrayList;

@Component
public class DataLoader implements ApplicationRunner {

    @Autowired
    BreederRepository breederRepository;

    @Autowired
    ListingRepository listingRepository;

    @Autowired
    UserRepository userRepository;

    @Autowired
    DogRepository dogRepository;

    @Autowired
    private PasswordEncoder passwordEncoder;

    public DataLoader(){

    }

    public void run(ApplicationArguments args) {

        ArrayList<String> dogs = new ArrayList<String>();
        dogs.add("Affenpinscher");
        dogs.add("Afghan Hound");
        dogs.add("Airedale Terrier");
        dogs.add("Akita");
        dogs.add("Alaskan Malamute");
        dogs.add("Anatolian Shepherd Dog");
        dogs.add("Australian Cattle Dog");
        dogs.add("Australian Shepherd");
        dogs.add("Australian Silky Terrier");
        dogs.add("Australian Terrier");
        dogs.add("Azawakh");
        dogs.add("Barbet");
        dogs.add("Basenji");
        dogs.add("Basset Bleu De Gascogne");
        dogs.add("Basset Fauve De Bretagne");
        dogs.add("Basset Griffon Vendeen (Grand)");
        dogs.add("Basset Griffon Vendeen (Petit)");
        dogs.add("Basset Hound");
        dogs.add("Bavarian Mountain Hound");
        dogs.add("Beagle");
        dogs.add("Bearded Collie");
        dogs.add("Beauceron");
        dogs.add("Bedlington Terrier");
        dogs.add("Belgian Shepherd Dog (Groenendael)");
        dogs.add("Belgian Shepherd Dog (Laekenois)");
        dogs.add("Belgian Shepherd Dog (Malinois)");
        dogs.add("Belgian Shepherd Dog (Tervueren)");
        dogs.add("Bergamasco");
        dogs.add("Bernese Mountain Dog");
        dogs.add("Bichon Frise");
        dogs.add("Black & Tan Coonhound");
        dogs.add("Bloodhound");
        dogs.add("Bolognese");
        dogs.add("Border Collie");
        dogs.add("Border Terrier");
        dogs.add("Borzoi");
        dogs.add("Boston Terrier");
        dogs.add("Bouvier Des Flandres");
        dogs.add("Boxer");
        dogs.add("Bracco Italiano");
        dogs.add("Braque D’Auvergne");
        dogs.add("Briard");
        dogs.add("Brittany");
        dogs.add("Bull Terrier");
        dogs.add("Bull Terrier (Miniature)");
        dogs.add("Bulldog");
        dogs.add("Bullmastiff");
        dogs.add("Cairn Terrier");
        dogs.add("Canaan Dog");
        dogs.add("Canadian Eskimo Dog");
        dogs.add("Catalan Sheepdog");
        dogs.add("Cavalier King Charles Spaniel");
        dogs.add("Cesky Terrier");
        dogs.add("Chihuahua (Long Coat)");
        dogs.add("Chihuahua (Smooth Coat)");
        dogs.add("Chinese Crested");
        dogs.add("Chow Chow");
        dogs.add("Cirneco Dell'Etna");
        dogs.add("Collie (Rough)");
        dogs.add("Collie (Smooth)");
        dogs.add("Coton De Tulear");
        dogs.add("Dachshund (Long Haired)");
        dogs.add("Dachshund (Miniature Long Haired)");
        dogs.add("Dachshund (Miniature Smooth Haired)");
        dogs.add("Dachshund (Miniature Wire Haired)");
        dogs.add("Dachshund (Smooth Haired)");
        dogs.add("Dachshund (Wire Haired)");
        dogs.add("Dalmatian");
        dogs.add("Dandie Dinmont Terrier");
        dogs.add("Deerhound");
        dogs.add("Dobermann");
        dogs.add("Dogue de Bordeaux");
        dogs.add("English Setter");
        dogs.add("English Toy Terrier (Black & Tan)");
        dogs.add("Entlebucher Mountain Dog");
        dogs.add("Estrela Mountain Dog");
        dogs.add("Eurasier");
        dogs.add("Finnish Lapphund");
        dogs.add("Finnish Spitz");
        dogs.add("Fox Terrier (Smooth)");
        dogs.add("Fox Terrier (Wire)");
        dogs.add("Foxhound");
        dogs.add("French Bulldog");
        dogs.add("German Longhaired Pointer");
        dogs.add("German Pinscher");
        dogs.add("German Shepherd Dog");
        dogs.add("German Shorthaired Pointer");
        dogs.add("German Spitz (Klein)");
        dogs.add("German Spitz (Mittel)");
        dogs.add("German Wirehaired Pointer");
        dogs.add("Giant Schnauzer");
        dogs.add("Glen Of Imaal Terrier");
        dogs.add("Gordon Setter");
        dogs.add("Grand Bleu De Gascogne");
        dogs.add("Great Dane");
        dogs.add("Great Swiss Mountain Dog");
        dogs.add("Greenland Dog");
        dogs.add("Greyhound");
        dogs.add("Griffon Bruxellois");
        dogs.add("Griffon Fauve De Bretagne");
        dogs.add("Hamiltonstovare");
        dogs.add("Harrier");
        dogs.add("Havanese");
        dogs.add("Hovawart");
        dogs.add("Hungarian Kuvasz");
        dogs.add("Hungarian Puli");
        dogs.add("Hungarian Pumi");
        dogs.add("Hungarian Vizsla");
        dogs.add("Hungarian Wire Haired Vizsla");
        dogs.add("Ibizan Hound");
        dogs.add("Irish Red & White Setter");
        dogs.add("Irish Setter");
        dogs.add("Irish Terrier");
        dogs.add("Irish Wolfhound");
        dogs.add("Italian Greyhound");
        dogs.add("Italian Spinone");
        dogs.add("Jack Russell Terrier");
        dogs.add("Japanese Akita Inu");
        dogs.add("Japanese Chin");
        dogs.add("Japanese Shiba Inu");
        dogs.add("Japanese Spitz");
        dogs.add("Keeshond");
        dogs.add("Kerry Blue Terrier");
        dogs.add("King Charles Spaniel");
        dogs.add("Komondor");
        dogs.add("Kooikerhondje");
        dogs.add("Korean Jindo");
        dogs.add("Korthals Griffon");
        dogs.add("Lagotto Romagnolo");
        dogs.add("Lakeland Terrier");
        dogs.add("Lancashire Heeler");
        dogs.add("Large Munsterlander");
        dogs.add("Leonberger");
        dogs.add("Lhasa Apso");
        dogs.add("Lowchen (Little Lion Dog)");
        dogs.add("Maltese");
        dogs.add("Manchester Terrier");
        dogs.add("Maremma Sheepdog");
        dogs.add("Mastiff");
        dogs.add("Miniature Pinscher");
        dogs.add("Miniature Schnauzer");
        dogs.add("Neapolitan Mastiff");
        dogs.add("Newfoundland");
        dogs.add("Norfolk Terrier");
        dogs.add("Norwegian Buhund");
        dogs.add("Norwegian Elkhound");
        dogs.add("Norwich Terrier");
        dogs.add("Old English Sheepdog");
        dogs.add("Otterhound");
        dogs.add("Papillon");
        dogs.add("Parson Russell Terrier");
        dogs.add("Pekingese");
        dogs.add("Pharaoh Hound");
        dogs.add("Picardy Sheepdog");
        dogs.add("Pointer");
        dogs.add("Polish Lowland Sheepdog");
        dogs.add("Pomeranian");
        dogs.add("Poodle (Miniature)");
        dogs.add("Poodle (Standard)");
        dogs.add("Poodle (Toy)");
        dogs.add("Portuguese Podengo");
        dogs.add("Portuguese Pointer");
        dogs.add("Portuguese Water Dog");
        dogs.add("Pug");
        dogs.add("Pyrenean Mastiff");
        dogs.add("Pyrenean Mountain Dog");
        dogs.add("Pyrenean Sheepdog (Long Haired)");
        dogs.add("Retriever (Chesapeake Bay)");
        dogs.add("Retriever (Curly Coated)");
        dogs.add("Retriever (Flat Coated)");
        dogs.add("Retriever (Golden)");
        dogs.add("Retriever (Labrador)");
        dogs.add("Retriever (Nova Scotia Duck Tolling)");
        dogs.add("Rhodesian Ridgeback");
        dogs.add("Rottweiler");
        dogs.add("Russian Black Terrier");
        dogs.add("Russian Toy");
        dogs.add("Saluki");
        dogs.add("Samoyed");
        dogs.add("Schipperke");
        dogs.add("Schnauzer");
        dogs.add("Scottish Terrier");
        dogs.add("Sealyham Terrier");
        dogs.add("Segugio Italiano");
        dogs.add("Shar Pei");
        dogs.add("Shetland Sheepdog");
        dogs.add("Shih Tzu");
        dogs.add("Siberian Husky");
        dogs.add("Skye Terrier");
        dogs.add("Sloughi");
        dogs.add("Slovakian Rough Haired Pointer");
        dogs.add("Small Munsterlander");
        dogs.add("Soft Coated Wheaten Terrier");
        dogs.add("Spaniel (American Cocker)");
        dogs.add("Spaniel (American Water)");
        dogs.add("Spaniel (Clumber)");
        dogs.add("Spaniel (Cocker)");
        dogs.add("Spaniel (English Springer)");
        dogs.add("Spaniel (Field)");
        dogs.add("Spaniel (Irish Water)");
        dogs.add("Spaniel (Sussex)");
        dogs.add("Spaniel (Welsh Springer)");
        dogs.add("Spanish Water Dog");
        dogs.add("St. Bernard");
        dogs.add("Staffordshire Bull Terrier");
        dogs.add("Swedish Lapphund");
        dogs.add("Swedish Vallhund");
        dogs.add("Tibetan Mastiff");
        dogs.add("Tibetan Spaniel");
        dogs.add("Tibetan Terrier");
        dogs.add("Turkish Kangal Dog");
        dogs.add("Weimaraner");
        dogs.add("Welsh Corgi (Cardigan)");
        dogs.add("Welsh Corgi (Pembroke)");
        dogs.add("Welsh Terrier");
        dogs.add("West Highland White Terrier");
        dogs.add("Whippet");
        dogs.add("White Swiss Shepherd Dog");
        dogs.add("Xoloitzcuintle (Mex Hairless) Int");
        dogs.add("Xoloitzcuintle (Mex Hairless) Min");
        dogs.add("Xoloitzcuintle (Mex Hairless) Std");
        dogs.add("Yorkshire Terrier");

        ArrayList<String> famalies = new ArrayList<String>();
        famalies.add("Toy Group");
        famalies.add("Hound Group");
        famalies.add("Terrier Group");
        famalies.add("Utility Group");
        famalies.add("Working Group");
        famalies.add("Pastoral Group");
        famalies.add("Pastoral Group");
        famalies.add("Pastoral Group");
        famalies.add("Toy Group");
        famalies.add("Terrier Group");
        famalies.add("Hound Group");
        famalies.add("Gundog Group");
        famalies.add("Hound Group");
        famalies.add("Hound Group");
        famalies.add("Hound Group");
        famalies.add("Hound Group");
        famalies.add("Hound Group");
        famalies.add("Hound Group");
        famalies.add("Hound Group");
        famalies.add("Hound Group");
        famalies.add("Pastoral Group");
        famalies.add("Pastoral Group");
        famalies.add("Terrier Group");
        famalies.add("Pastoral Group");
        famalies.add("Pastoral Group");
        famalies.add("Pastoral Group");
        famalies.add("Pastoral Group");
        famalies.add("Pastoral Group");
        famalies.add("Working Group");
        famalies.add("Toy Group");
        famalies.add("Hound Group");
        famalies.add("Hound Group");
        famalies.add("Toy Group");
        famalies.add("Pastoral Group");
        famalies.add("Terrier Group");
        famalies.add("Hound Group");
        famalies.add("Utility Group");
        famalies.add("Working Group");
        famalies.add("Working Group");
        famalies.add("Gundog Group");
        famalies.add("Gundog Group");
        famalies.add("Pastoral Group");
        famalies.add("Gundog Group");
        famalies.add("Terrier Group");
        famalies.add("Terrier Group");
        famalies.add("Utility Group");
        famalies.add("Working Group");
        famalies.add("Terrier Group");
        famalies.add("Utility Group");
        famalies.add("Working Group");
        famalies.add("Pastoral Group");
        famalies.add("Toy Group");
        famalies.add("Terrier Group");
        famalies.add("Toy Group");
        famalies.add("Toy Group");
        famalies.add("Toy Group");
        famalies.add("Utility Group");
        famalies.add("Hound Group");
        famalies.add("Pastoral Group");
        famalies.add("Pastoral Group");
        famalies.add("Toy Group");
        famalies.add("Hound Group");
        famalies.add("Hound Group");
        famalies.add("Hound Group");
        famalies.add("Hound Group");
        famalies.add("Hound Group");
        famalies.add("Hound Group");
        famalies.add("Utility Group");
        famalies.add("Terrier Group");
        famalies.add("Hound Group");
        famalies.add("Working Group");
        famalies.add("Working Group");
        famalies.add("Gundog Group");
        famalies.add("Toy Group");
        famalies.add("Working Group");
        famalies.add("Pastoral Group");
        famalies.add("Utility Group");
        famalies.add("Pastoral Group");
        famalies.add("Hound Group");
        famalies.add("Terrier Group");
        famalies.add("Terrier Group");
        famalies.add("Hound Group");
        famalies.add("Utility Group");
        famalies.add("Gundog Group");
        famalies.add("Working Group");
        famalies.add("Pastoral Group");
        famalies.add("Gundog Group");
        famalies.add("Utility Group");
        famalies.add("Utility Group");
        famalies.add("Gundog Group");
        famalies.add("Working Group");
        famalies.add("Terrier Group");
        famalies.add("Gundog Group");
        famalies.add("Hound Group");
        famalies.add("Working Group");
        famalies.add("Working Group");
        famalies.add("Working Group");
        famalies.add("Hound Group");
        famalies.add("Toy Group");
        famalies.add("Hound Group");
        famalies.add("Hound Group");
        famalies.add("Hound Group");
        famalies.add("Toy Group");
        famalies.add("Working Group");
        famalies.add("Pastoral Group");
        famalies.add("Pastoral Group");
        famalies.add("Pastoral Group");
        famalies.add("Gundog Group");
        famalies.add("Gundog Group");
        famalies.add("Hound Group");
        famalies.add("Gundog Group");
        famalies.add("Gundog Group");
        famalies.add("Terrier Group");
        famalies.add("Hound Group");
        famalies.add("Toy Group");
        famalies.add("Gundog Group");
        famalies.add("Terrier Group");
        famalies.add("Utility Group");
        famalies.add("Toy Group");
        famalies.add("Utility Group");
        famalies.add("Utility Group");
        famalies.add("Utility Group");
        famalies.add("Terrier Group");
        famalies.add("Toy Group");
        famalies.add("Pastoral Group");
        famalies.add("Utility Group");
        famalies.add("Utility Group");
        famalies.add("Gundog Group");
        famalies.add("Gundog Group");
        famalies.add("Terrier Group");
        famalies.add("Pastoral Group");
        famalies.add("Gundog Group");
        famalies.add("Working Group");
        famalies.add("Utility Group");
        famalies.add("Toy Group");
        famalies.add("Toy Group");
        famalies.add("Terrier Group");
        famalies.add("Pastoral Group");
        famalies.add("Working Group");
        famalies.add("Toy Group");
        famalies.add("Utility Group");
        famalies.add("Working Group");
        famalies.add("Working Group");
        famalies.add("Terrier Group");
        famalies.add("Pastoral Group");
        famalies.add("Hound Group");
        famalies.add("Terrier Group");
        famalies.add("Pastoral Group");
        famalies.add("Hound Group");
        famalies.add("Toy Group");
        famalies.add("Terrier Group");
        famalies.add("Toy Group");
        famalies.add("Hound Group");
        famalies.add("Pastoral Group");
        famalies.add("Gundog Group");
        famalies.add("Pastoral Group");
        famalies.add("Toy Group");
        famalies.add("Utility Group");
        famalies.add("Utility Group");
        famalies.add("Utility Group");
        famalies.add("Hound Group");
        famalies.add("Gundog Group");
        famalies.add("Working Group");
        famalies.add("Toy Group");
        famalies.add("Working Group");
        famalies.add("Pastoral Group");
        famalies.add("Pastoral Group");
        famalies.add("Gundog Group");
        famalies.add("Gundog Group");
        famalies.add("Gundog Group");
        famalies.add("Gundog Group");
        famalies.add("Gundog Group");
        famalies.add("Gundog Group");
        famalies.add("Hound Group");
        famalies.add("Working Group");
        famalies.add("Working Group");
        famalies.add("Toy Group");
        famalies.add("Hound Group");
        famalies.add("Pastoral Group");
        famalies.add("Utility Group");
        famalies.add("Utility Group");
        famalies.add("Terrier Group");
        famalies.add("Terrier Group");
        famalies.add("Hound Group");
        famalies.add("Utility Group");
        famalies.add("Pastoral Group");
        famalies.add("Utility Group");
        famalies.add("Working Group");
        famalies.add("Terrier Group");
        famalies.add("Hound Group");
        famalies.add("Gundog Group");
        famalies.add("Gundog Group");
        famalies.add("Terrier Group");
        famalies.add("Gundog Group");
        famalies.add("Gundog Group");
        famalies.add("Gundog Group");
        famalies.add("Gundog Group");
        famalies.add("Gundog Group");
        famalies.add("Gundog Group");
        famalies.add("Gundog Group");
        famalies.add("Gundog Group");
        famalies.add("Gundog Group");
        famalies.add("Gundog Group");
        famalies.add("Working Group");
        famalies.add("Terrier Group");
        famalies.add("Pastoral Group");
        famalies.add("Pastoral Group");
        famalies.add("Working Group");
        famalies.add("Utility Group");
        famalies.add("Utility Group");
        famalies.add("Pastoral Group");
        famalies.add("Gundog Group");
        famalies.add("Pastoral Group");
        famalies.add("Pastoral Group");
        famalies.add("Terrier Group");
        famalies.add("Terrier Group");
        famalies.add("Hound Group");
        famalies.add("Pastoral Group");
        famalies.add("Utility Group");
        famalies.add("Utility Group");
        famalies.add("Utility Group");
        famalies.add("Toy Group");



        for (int i = 0; i < dogs.size(); i++){
            Dog dog = new Dog(dogs.get(i), "size_goes_here", famalies.get(i));
            dogRepository.save(dog);
        }




        String password1 = passwordEncoder.encode("passw");
        String password2 = passwordEncoder.encode("breed");

        User user = new User("Jay", password1);
        userRepository.save(user);

        Breeder breeder1 = new Breeder("Dave", password2, "101");
        breederRepository.save(breeder1);

        Breeder ash = new Breeder("Ash", password2, "104");
        breederRepository.save(ash);

        Dog border = new Dog("Border Terrier", "Medium", "Terrier");
        dogRepository.save(border);
        Dog alsatian = new Dog("German Sheppard", "Large", "Working Dog");
        dogRepository.save(alsatian);
        Dog bernard = new Dog("St Bernard", "Large", "Working Dog");
        dogRepository.save(bernard);
        Dog chihuahua = new Dog("Chihuahua", "Small", "Toy");
        dogRepository.save(chihuahua);
//
        Listing listing1 = new Listing("Larry", 120, 2, alsatian, breeder1);
        listingRepository.save(listing1);

        Listing listing2 = new Listing("Buster", 70, 1, border, breeder1);
        listingRepository.save(listing2);

        Listing listing3 = new Listing("Ratly", 30, 1, chihuahua, ash);
        listingRepository.save(listing3);

    }

}
